/**
 * CSRF-state cookie for the Google OAuth redirect flow (Phase 5's
 * additive login path). A short-lived, scoped sibling to
 * `refresh-cookie.ts` — different name/path/lifetime, so kept in its
 * own file rather than overloading that one.
 *
 * The state value itself is generated by the route (`crypto.randomBytes`,
 * same primitive already used for refresh tokens) — this file only
 * owns storing/reading/clearing it as a cookie across the redirect to
 * Google and back.
 */

import { parse } from 'cookie';
import type { Request, Response } from 'express';

const OAUTH_STATE_COOKIE_NAME = 'googleOauthState';
/** Scoped to the two Google OAuth routes only. */
const OAUTH_STATE_COOKIE_PATH = '/api/auth/google';
/** Generous enough for a user to actually complete Google's consent screen, short enough to limit replay risk. */
const OAUTH_STATE_MAX_AGE_MS = 10 * 60 * 1000;

export function setOAuthStateCookie(res: Response, state: string): void {
  res.cookie(OAUTH_STATE_COOKIE_NAME, state, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    path: OAUTH_STATE_COOKIE_PATH,
    maxAge: OAUTH_STATE_MAX_AGE_MS,
  });
}

export function clearOAuthStateCookie(res: Response): void {
  res.clearCookie(OAUTH_STATE_COOKIE_NAME, { path: OAUTH_STATE_COOKIE_PATH });
}

export function readOAuthStateCookie(req: Request): string | null {
  const header = req.headers.cookie;
  if (header === undefined) return null;
  return parse(header)[OAUTH_STATE_COOKIE_NAME] ?? null;
}
