version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: astranet_db
    environment:
      POSTGRES_USER: astra_admin
      POSTGRES_PASSWORD: astra_secret
      POSTGRES_DB: astranet
    ports:
      - "5433:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: astranet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  timescaledb_data:
  redis_data:
